# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1b50rc8c9yp5l0aw0cq5zp7p3pcschfmrq0bp5z0blsqv3cb2j4i";
    aarch64-linux = "1ysd4kvfgb3xz8yjwxzlw1znpwd1l12i7hswz852n6p9ik9rx63p";
    x86_64-darwin = "06xhx8b98spyxv6dlbf04nvys2lzzxfp5qqx15j6mysi46k8s52p";
    aarch64-darwin = "0vfyfq1f2rv4wl8cs6gpxj1x2rgb7815jx0dvyyjyc1p5dgiccmi";
  };

  urlMap = {
    x86_64-linux = "https://github.com/MGM-Laboratory/mgm-cli/releases/download/v0.4.8/mgm-linux-amd64.tar.gz";
    aarch64-linux = "https://github.com/MGM-Laboratory/mgm-cli/releases/download/v0.4.8/mgm-linux-arm64.tar.gz";
    x86_64-darwin = "https://github.com/MGM-Laboratory/mgm-cli/releases/download/v0.4.8/mgm-darwin-amd64.tar.gz";
    aarch64-darwin = "https://github.com/MGM-Laboratory/mgm-cli/releases/download/v0.4.8/mgm-darwin-arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "mgm";
  version = "0.4.8";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./mgm $out/bin/mgm
  '';

  meta = {
    description = "Megumi Code — the MGM Laboratory CLI (mgm)";
    homepage = "https://github.com/MGM-Laboratory/mgm-cli";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
