# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1gw4v81y0rh9i789kj8yvlrb08dsxkmswkkmi0a4mjg64ab67mc1";
    aarch64-linux = "0gfm5vngqgdplypam8j4bd3xfpnm2r9rg03y5wj688p1ahwwfdhi";
    x86_64-darwin = "04xs0lkw3lyy753ck6ypcwy63i1w30c762l9y01a50664sw7isr6";
    aarch64-darwin = "0mp2pkmlzvyn40lhgmwgh27xwlrvz59asbr89lx9mc4vswar9ypy";
  };

  urlMap = {
    x86_64-linux = "https://github.com/MGM-Laboratory/mgm-cli/releases/download/v0.2.1/mgm-linux-amd64.tar.gz";
    aarch64-linux = "https://github.com/MGM-Laboratory/mgm-cli/releases/download/v0.2.1/mgm-linux-arm64.tar.gz";
    x86_64-darwin = "https://github.com/MGM-Laboratory/mgm-cli/releases/download/v0.2.1/mgm-darwin-amd64.tar.gz";
    aarch64-darwin = "https://github.com/MGM-Laboratory/mgm-cli/releases/download/v0.2.1/mgm-darwin-arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "mgm";
  version = "0.2.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./mgm $out/bin/mgm
  '';

  meta = {
    description = "Megumi Code — the MGM Laboratory CLI (mgm)";
    homepage = "https://github.com/MGM-Laboratory/mgm-cli";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
